config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: {
    passwords: 'devise/passwords'
  }

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :meeting_rooms, only: [:index, :show]

  resources :bookings, only: [:index, :new, :create, :show, :destroy] do
    member do
      patch :cancel_booking
    end
  end

  namespace :admin do
    root to: 'dashboard#index'  
    get 'dashboard', to: 'dashboard#index', as: :admin_dashboard
    
    resources :meeting_rooms  
    resources :bookings, only: [:index]
  end
end

app/models/meeting_room.rb
class MeetingRoom < ApplicationRecord
    has_many :bookings, dependent: :destroy
  
    validates :name, presence: true, uniqueness: true
    validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  end
  

app/controllers/admin/meeting_rooms_controller.rb
class Admin::MeetingRoomsController < ApplicationController
    
  before_action :authenticate_user!
  before_action :authorize_admin!, only: [:index, :new, :create, :edit, :update, :destroy]
  
  before_action :set_meeting_room, only: [:edit, :update, :show, :destroy]
 


  def index
    @meeting_rooms = MeetingRoom.all 
    Rails.logger.debug "Meeting Rooms: #{@meeting_rooms.inspect}"
  end
  
  def show
    @meeting_room = MeetingRoom.find(params[:id])
  end

  def new
    @meeting_room = MeetingRoom.new
  end

  def create
    @meeting_room = MeetingRoom.new(meeting_room_params)
    if @meeting_room.save
      redirect_to admin_meeting_rooms_path, notice: "Meeting room added successfully!"
    else
      render :new
    end
  end

  def edit
    @meeting_room = MeetingRoom.find(params[:id])
  end

  def update
    @meeting_room = MeetingRoom.find(params[:id])
    if @meeting_room.update(meeting_room_params)
      redirect_to admin_meeting_rooms_path, notice: "Meeting room updated successfully!"
    else
      render :edit
    end
  end
  def destroy
    @meeting_room.destroy
    respond_to do |format|
      format.html { redirect_to admin_meeting_rooms_path, notice: "Meeting room was successfully deleted." }
      format.json { head :no_content }
    end
  end
  
  private
  def set_booking
    @booking = Booking.find(params[:id])
  end
  def meeting_room_params
    params.require(:meeting_room).permit(:name, :capacity)
  end

  def authorize_admin!
    redirect_to root_path, alert: 'Access denied!' unless current_user.admin?
  end
end
def set_meeting_room
  @meeting_room = MeetingRoom.find(params[:id])
end

app/controllers/meeting_rooms_controller.rb
class MeetingRoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting_room, only: [:available_slots]

  def index
    @meeting_rooms = MeetingRoom.all
  end
  
  def show
    @meeting_room = MeetingRoom.find(params[:id])
  end

  def available_slots
    booked_slots = @meeting_room.bookings.pluck(:start_time, :end_time)
    all_slots = generate_half_hour_slots

    available_slots = all_slots.reject do |slot|
      booked_slots.any? { |b| slot.between?(b[0], b[1]) }
    end

    render json: { available_slots: available_slots }
  end
  private

  def set_meeting_room
    @meeting_room = MeetingRoom.find(params[:id])
  end
def generate_half_hour_slots
  start_of_day = Time.zone.now.beginning_of_day + 9.hours 
  end_of_day = start_of_day + 9.hours 

  slots = []
  current_time = start_of_day
  while current_time < end_of_day
    slots << current_time
    current_time += 30.minutes
  end
  slots
end
end

app/views/admin/meeting_rooms/edit.html.erb
<h1>Edit Meeting Room</h1>

<%= form_with model: @meeting_room, url: admin_meeting_room_path(@meeting_room), local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div>
    <%= form.submit "Update Meeting Room" %>
  </div>
<% end %>

<%= link_to "Back", admin_meeting_rooms_path, class: "button" %>

app/views/admin/meeting_rooms/index.html.erb
<h1>Meeting Rooms</h1>

<%= link_to "Add New Room", new_admin_meeting_room_path, class: "button" %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Capacity</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @meeting_rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.capacity %> people</td>
        <td>
          <%= link_to "Edit", edit_admin_meeting_room_path(room), class: "button" %>
          <%= link_to "Delete", admin_meeting_room_path(room), method: :delete, data: { confirm: "Are you sure?" }, class: "button delete-button" %>
 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/meeting_rooms/new.html.erb
<h1>Add New Meeting Room</h1>

<%= form_with model: @meeting_room, url: admin_meeting_rooms_path, local: true do |form| %>
  <div>
    <%= form.label :name, "Room Name" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :capacity, "Capacity" %>
    <%= form.number_field :capacity, required: true %>
  </div>

  <div>
    <%= form.submit "Create Room", class: "button" %>
  </div>
<% end %>

<%= link_to "Back", admin_meeting_rooms_path, class: "button" %>