config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: {
    passwords: 'devise/passwords'
  }

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :meeting_rooms, only: [:index, :show]

  resources :bookings, only: [:index, :new, :create, :show, :destroy] do
    member do
      patch :cancel_booking
    end
  end

  namespace :admin do
    root to: 'dashboard#index'  
    get 'dashboard', to: 'dashboard#index', as: :admin_dashboard
    
    resources :meeting_rooms  
    resources :bookings, only: [:index]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meeting Room Booking</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "admin_bookings", media: "all" if controller_path.start_with?('admin/') %>
  <%= stylesheet_link_tag "admin_dashboard", media: "all" if controller_path.start_with?('admin/') %>
  <%= stylesheet_link_tag "bookings", media: "all" %>

  <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
 

  <%= javascript_importmap_tags %>
</head>
<body>
<header>
<div class="container">
<nav>
  <% if user_signed_in? %>
  

<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  
  <% else %>
    <%= link_to 'Sign Up', new_user_registration_path %> | 
    <%= link_to "Login", new_user_session_path %> |
  <% end %>
</nav>
</div>
</header>
  <main>
    <%= yield %>
  </main>
</body>

<script>
  document.addEventListener("turbo:load", function() {
    document.querySelectorAll('a[data-turbo-method="delete"]').forEach(el => {
      el.addEventListener('click', function(event) {
        event.preventDefault();
        if (confirm("Are you sure you want to log out?")) {
          fetch(el.href, { 
            method: 'DELETE', 
            headers: { 'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content } 
          }).then(() => window.location.href = "/");
        }
      });
    });
  });
</script>

</html>